### ISSUE TITLE
hang on truncated lines

### ISSUE THREAD

**Issue by vixns** [gforcada/haproxy_log_analysis#23]
Request uris may be truncated in haproxy logs.
The default is a 1024 characters limit, so you may not have the final space and protocol.

When passing a truncated line to `Line()`, the process stales with a high cpu usage.
A quick fix is to make it optional.

https://github.com/gforcada/haproxy_log_analysis/blob/master/haproxy/line.py#L63

`r'(\s+(?P<protocol>\w+/\d\.\d))?'`

**Comment by gforcada** [comment]
@vixns thanks for reporting and looking for a solution!

Sorry for the late reply, I was on vacations, would you mind providing a pull request with these changes? Thanks in advance!

**Comment by gforcada** [comment]
Fixed on #37 and about to be released :)
