### ISSUE TITLE
zero lines parsed

### ISSUE THREAD

**Issue by bsimm** [gforcada/haproxy_log_analysis#28]
Hi, I'm having an issue parsing my log file. Here's the output:
```
$ haproxy_log_analysis -l screenlog.log -c counter
command: counter
================
0
$ rm screenlog.log.pickle
$ haproxy_log_analysis -l screenlog.log -c counter
command: counter
================
0
```
Here's a sample line from my log file (sensitive info scrubbed):

`2017/07/19 14:47:47 <local0,info> SOME.IP:PORT [19/Jul/2017:14:47:47.805] http-in test/upstream 0/0/1/3/4 200 251 - - ---- 1/1/0/1/0 0/0 "POST /SOME/URL HTTP/1.1"`

**Comment by gforcada** [comment]
@bsimm hi! Thanks for using haproxy_log_analysis and for taking the time to report issues!

I will try to have a look, although I'm rather busy right now.

Do you have, by any chance, python skills? You could check the regular expressions used to parse the log lines https://github.com/gforcada/haproxy_log_analysis/blob/master/haproxy/line.py#L26-L79

**Comment by bsimm** [comment]
Ah yes, It's definitely a regex mismatch. Thanks.
