### ISSUE TITLE
Not getting expected result?

### ISSUE THREAD

**Issue by jason-ryan** [gforcada/haproxy_log_analysis#9]
Hi,

I could be doing something wrong - but I wanted to use the haproxy log analyzer and I'm getting unexpected output.

> haproxy_log_analysis -l haproxy.log -c server_load
command: server_load
====================
defaultdict(<type 'int'>, {})

The haproxy logs are in the httplog format - any help would be appreciated!

Thanks,
Jason

**Comment by gforcada** [comment]
Hi,

first of all thanks for using the project!

And now to the bug:
would it be possible to get a sample of your log file? Or even better, could you keep reducing your log file until you get the smallest possible log file that triggers the bug?

Another possibility, could it be that the pickled file using on the nth run of it was a stale one? haproxy_log_analysis creates a pickle file out of the log file to speed up any further call, so the first run is a bit slow but then it's much much faster. Could you remove that file and try again? The pickle file is the name of the log file with a ``.pickle`` extension appended to it.

**Comment by jason-ryan** [comment]
Thanks for the reply!
I tried deleting the the pickle file, but still no luck.

I tailed out the haproxy log to another file and that didn't either.

I've attached an example haproxy file that I'm trying to use the tool
against.

Thanks!
Jason


[image: photo]
*Jason Ryan*
VP Engineering

Trustev
Real Time, Online Identity Verification

email: jason.ryan@trustev.com
skype: jason_j_ryan
web: www.trustev.com

Trustev Ltd, 2100 Cork Airport Business Park, Cork, Ireland.

On 20 March 2015 at 23:36, Gil Forcada <notifications@github.com> wrote:

> Hi,
>
> first of all thanks for using the project!
>
> And now to the bug:
> would it be possible to get a sample of your log file? Or even better,
> could you keep reducing your log file until you get the smallest possible
> log file that triggers the bug?
>
> Another possibility, could it be that the pickled file using on the nth
> run of it was a stale one? haproxy_log_analysis creates a pickle file out
> of the log file to speed up any further call, so the first run is a bit
> slow but then it's much much faster. Could you remove that file and try
> again? The pickle file is the name of the log file with a .pickle
> extension appended to it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gforcada/haproxy_log_analysis/issues/9#issuecomment-84195401>
> .
>

-- 


This message is for the named person's use only. If you received this 
message in error, please immediately delete it and all copies and notify 
the sender. You must not, directly or indirectly, use, disclose, 
distribute, print, or copy any part of this message if you are not the 
intended recipient. Any views expressed in this message are those of the 
individual sender and not Trustev Ltd. Trustev is registered in Ireland No. 
516425 and trades from 2100 Cork Airport Business Park, Cork, Ireland.

10.0.2.7:58500 [22/Mar/2015:16:44:27.021] riak_rest riak_rest_backend/TRV-EU-RIAK-7 0/0/1/830/831 200 1217 - - ---- 50/50/49/8/0 0/0 "GET /search/query/sessions?q=Session.Details.IPAddresses.ClientIp:101.190.106.132&fl=Session.SessionId&wt=json&sort=&start=0&rows=10000000 HTTP/1.1"
 10.0.2.15:51771 [22/Mar/2015:16:44:27.144] riak_rest riak_rest_backend/TRV-EU-RIAK-7 0/0/1/710/711 400 1654 - - ---- 49/49/48/8/0 0/0 "GET /search/query/sessions?q=Session.Devices.DeviceFingerprints.DeviceTag:--------9C16D991C79C6330E655AA29EA623492-38B3EFF8BAF56627478EC76A704E9B52-38B3EFF8BAF56627478EC76A704E9B52-%20AND%20Session.Cases.Statuses.Status:ChargebackFraud&wt=json&sort=&start=0&rows=0 HTTP/1.1"
 10.0.2.15:51429 [22/Mar/2015:16:44:12.808] riak_rest riak_rest_backend/TRV-EU-RIAK-8 1/0/1/15046/15048 200 1153 - - ---- 49/49/48/17/0 0/0 "GET /search/query/sessions?q=Session.Details.IPAddresses.ClientIp:74.89.103.122&fl=Session.SessionId&wt=json&sort=&start=0&rows=10000000 HTTP/1.1"
 10.0.2.7:58445 [22/Mar/2015:16:44:24.416] riak_rest riak_rest_backend/TRV-EU-RIAK-8 0/0/1/3481/3482 200 1642 - - ---- 48/48/47/15/0 0/0 "GET /search/query/sessions?q=Session.Details.IPAddresses.ClientIp:98.202.31.19&fl=Session.SessionId&wt=json&sort=&start=0&rows=10000000 HTTP/1.1"
 10.0.2.14:59417 [22/Mar/2015:16:44:27.899] riak_rest riak_rest_backend/TRV-EU-RIAK-6 0/0/1/3/4 500 1397 - - ---- 50/50/49/9/0 0/0 "GET /search/query/sessions?q=Session.Details.IPAddresses.ClientIp:184.191.61.77&fl=Session.SessionId&wt=json&sort=&start=0&rows=10000000 HTTP/1.1"
 10.0.2.14:59401 [22/Mar/2015:16:44:27.540] riak_rest riak_rest_backend/TRV-EU-RIAK-9 0/0/0/401/401 200 1337 - - ---- 50/50/49/7/0 0/0 "GET /search/query/sessions?q=Session.Details.IPAddresses.ClientIp:72.173.209.71&fl=Session.SessionId&wt=json&sort=&start=0&rows=10000000 HTTP/1.1"
 10.0.2.7:58529 [22/Mar/2015:16:44:27.900] riak_rest riak_rest_backend/TRV-EU-RIAK-5 0/0/1/69/70 204 222 - - ---- 50/50/49/9/0 0/0 "PUT /types/Production/buckets/Trustev.Grains.Domain.SessionGrain/keys/4be2e8f1611a53099bf0e45c9498d48c03000000652e3695 HTTP/1.1"
 10.0.2.15:51789 [22/Mar/2015:16:44:27.977] riak_rest riak_rest_backend/TRV-EU-RIAK-6 0/0/0/3/3 404 195 - - ---- 51/51/50/10/0 0/0 "GET /types/Production/buckets/Trustev.Grains.Domain.TrustevCookieGrain/keys/4c535a70e97eda4ea6c8b566cb8527b80300000043a46a51 HTTP/1.1"
 10.0.2.7:58530 [22/Mar/2015:16:44:27.974] riak_rest riak_rest_backend/TRV-EU-RIAK-9 0/0/0/6/6 404 195 - - ---- 51/51/49/7/0 0/0 "GET /types/Production/buckets/Trustev.Grains.Domain.SessionGrain/keys/46aa80ec2c9c03ead3202c4755a9b8be03000000652e3695 HTTP/1.1"
 10.0.2.7:58503 [22/Mar/2015:16:44:27.179] riak_rest riak_rest_backend/TRV-EU-RIAK-7 0/0/1/802/803 200 1093 - - ---- 51/51/48/9/0 0/0 "GET /search/query/sessions?q=Session.Details.IPAddresses.ClientIp:166.181.82.185&fl=Session.SessionId&wt=json&sort=&start=0&rows=10000000 HTTP/1.1"

**Comment by gforcada** [comment]
Thanks I will try to find some time to look into it.

**Comment by jethr0** [comment]
Hi folks,

same for me:
$ haproxy_log_analysis -l some-log-file -c http_methods
command: http_methods
=====================
defaultdict(<type 'int'>, {})

$ haproxy_log_analysis -l some-log-file --command top_request_paths
command: top_request_paths
==========================
[]

Logfile entries match the one  mentioned here http://cbonte.github.io/haproxy-dconv/configuration-1.4.html#8.2.3 except for the "captured_response_headers" which are not provided. Manually adding {} didn't change anything though.

Running python 2.7.3 on a default debian 7 box.

Any ideas on that?

**Comment by gforcada** [comment]
@jason-ryan @jethr0 I think I found the reason: all log files I had been working with so far were stored on syslog which prepends a timestamp on all log lines, see this example test file: https://github.com/gforcada/haproxy_log_analysis/blob/master/haproxy/tests/files/2_ok_1_invalid.log

I see that the log file you attached (@jason-ryan) does not have that and instead starts directly with the haproxy process name and pid.

If you prepend ``Dec  9 12:00:03 localhost haproxy[12345]: `` (note the trailing space) on all your log lines it works correctly.

The proper fix would be to completely ignore syslog information. Anyone willing to provide a patch? I don't have much time right now, but on the meantime you can prepend to all lines a fake syslog record so haproxy_log_analysis processes the log files.

Can you confirm that this works?

**Comment by jethr0** [comment]
@gforcada I used the "syslog style" as you described it, just like that:

Mar 8 01:00:00 127.0.0.1 haproxy[1234]: 127.0.0.1:1234 [08/Mar/2015:01:00:00.000] some_frontend some_backend/anyserver 0/0/0/1234/1234 200 123 - - ---- 0/0/0/0/0 0/0 {www.someurl.com|Mozilla/5.0 (some info) AppleWebKit/535.19 (even more info)|http://www.someurl.com/} "GET /some/path HTTP/1.1"

If I run the tool on a a file containing this single line, I get:
$ haproxy_log_analysis -l x -c http_methods
command: http_methods
=====================-
defaultdict(<type 'int'>, {})

**Comment by gforcada** [comment]
@jethr0 that's because of the first ``127.0.0.1`` in all haproxy_log_analysis tests, that's ``localhost`` so the regular expression was failing there.

I'm about to make a new release with that fix

**Comment by gforcada** [comment]
@jethr0 I just released version 1.0 can you give it a try? The same with you @jason-ryan

**Comment by jason-ryan** [comment]
Great - will give it a go now!

[image: photo]
*Jason Ryan*
VP Engineering

Trustev
Real Time, Online Identity Verification

email: jason.ryan@trustev.com
skype: jason_j_ryan
web: www.trustev.com

Trustev Ltd, 2100 Cork Airport Business Park, Cork, Ireland.

On 24 March 2015 at 15:33, Gil Forcada <notifications@github.com> wrote:

> @jethr0 <https://github.com/jethr0> I just released version 1.0 can you
> give it a try? The same with you @jason-ryan
> <https://github.com/jason-ryan>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gforcada/haproxy_log_analysis/issues/9#issuecomment-85559866>
> .
>

-- 


This message is for the named person's use only. If you received this 
message in error, please immediately delete it and all copies and notify 
the sender. You must not, directly or indirectly, use, disclose, 
distribute, print, or copy any part of this message if you are not the 
intended recipient. Any views expressed in this message are those of the 
individual sender and not Trustev Ltd. Trustev is registered in Ireland No. 
516425 and trades from 2100 Cork Airport Business Park, Cork, Ireland.

**Comment by jason-ryan** [comment]
Afraid no joy.

I just pulled the zip from
https://github.com/gforcada/haproxy_log_analysis/archive/master.zip
and ran the 'python setup.py install'

I got the same error

#haproxy_log_analysis -l haproxy.log.test -c ip_counter
command: ip_counter
===================
defaultdict(<type 'int'>, {})



[image: photo]
*Jason Ryan*
VP Engineering

Trustev
Real Time, Online Identity Verification

email: jason.ryan@trustev.com
skype: jason_j_ryan
web: www.trustev.com

Trustev Ltd, 2100 Cork Airport Business Park, Cork, Ireland.

On 24 March 2015 at 15:33, Gil Forcada <notifications@github.com> wrote:

> @jethr0 <https://github.com/jethr0> I just released version 1.0 can you
> give it a try? The same with you @jason-ryan
> <https://github.com/jason-ryan>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gforcada/haproxy_log_analysis/issues/9#issuecomment-85559866>
> .
>

-- 


This message is for the named person's use only. If you received this 
message in error, please immediately delete it and all copies and notify 
the sender. You must not, directly or indirectly, use, disclose, 
distribute, print, or copy any part of this message if you are not the 
intended recipient. Any views expressed in this message are those of the 
individual sender and not Trustev Ltd. Trustev is registered in Ireland No. 
516425 and trades from 2100 Cork Airport Business Park, Cork, Ireland.

**Comment by gforcada** [comment]
@jason-ryan could you paste one single line of your log file that shows that behavior?

That would help me a lot debugging. Thanks!

**Comment by jason-ryan** [comment]
Sure - I just ran it again on the cut down version again, but I'll cut that to the first line shortly and try again.

Thanks!

Sent from my iPhone

> On 24 Mar 2015, at 16:09, Gil Forcada <notifications@github.com> wrote:
> 
> @jason-ryan could you paste one single line of your log file that shows that behavior?
> 
> That would help me a lot debugging. Thanks!
> 
> —
> Reply to this email directly or view it on GitHub.
> 

-- 


This message is for the named person's use only. If you received this 
message in error, please immediately delete it and all copies and notify 
the sender. You must not, directly or indirectly, use, disclose, 
distribute, print, or copy any part of this message if you are not the 
intended recipient. Any views expressed in this message are those of the 
individual sender and not Trustev Ltd. Trustev is registered in Ireland No. 
516425 and trades from 2100 Cork Airport Business Park, Cork, Ireland.

**Comment by jason-ryan** [comment]
Single line haproxy example attached.

Thanks for taking the time to look at it!

Jason

[image: photo]
*Jason Ryan*
VP Engineering

Trustev
Real Time, Online Identity Verification

email: jason.ryan@trustev.com
skype: jason_j_ryan
web: www.trustev.com

Trustev Ltd, 2100 Cork Airport Business Park, Cork, Ireland.

On 24 March 2015 at 16:09, Gil Forcada <notifications@github.com> wrote:

> @jason-ryan <https://github.com/jason-ryan> could you paste one single
> line of your log file that shows that behavior?
>
> That would help me a lot debugging. Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gforcada/haproxy_log_analysis/issues/9#issuecomment-85583111>
> .
>

-- 


This message is for the named person's use only. If you received this 
message in error, please immediately delete it and all copies and notify 
the sender. You must not, directly or indirectly, use, disclose, 
distribute, print, or copy any part of this message if you are not the 
intended recipient. Any views expressed in this message are those of the 
individual sender and not Trustev Ltd. Trustev is registered in Ireland No. 
516425 and trades from 2100 Cork Airport Business Park, Cork, Ireland.

**Comment by gforcada** [comment]
@jason-ryan could you paste that into github directly, maybe the way you paste it on the email does not work because I don't see any line attached...

**Comment by jason-ryan** [comment]
10.0.2.7:58500 [22/Mar/2015:16:44:27.021] riak_rest riak_rest_backend/TRV-EU-RIAK-7 0/0/1/830/831 200 1217 - - ---- 50/50/49/8/0 0/0 "GET /search/query/sessions?q=Session.Details.IPAddresses.ClientIp:x&fl=Session.SessionId&wt=json&sort=&start=0&rows=10000000 HTTP/1.1"

**Comment by jason-ryan** [comment]
Hi Gil,
Just posted that now - hope that helps!

Thanks,
Jason

[image: photo]
*Jason Ryan*
VP Engineering

Trustev
Real Time, Online Identity Verification

email: jason.ryan@trustev.com
skype: jason_j_ryan
web: www.trustev.com

Trustev Ltd, 2100 Cork Airport Business Park, Cork, Ireland.

On 24 March 2015 at 19:55, Gil Forcada <notifications@github.com> wrote:

> @jason-ryan <https://github.com/jason-ryan> could you paste that into
> github directly, maybe the way you paste it on the email does not work
> because I don't see any line attached...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gforcada/haproxy_log_analysis/issues/9#issuecomment-85668039>
> .
>

-- 


This message is for the named person's use only. If you received this 
message in error, please immediately delete it and all copies and notify 
the sender. You must not, directly or indirectly, use, disclose, 
distribute, print, or copy any part of this message if you are not the 
intended recipient. Any views expressed in this message are those of the 
individual sender and not Trustev Ltd. Trustev is registered in Ireland No. 
516425 and trades from 2100 Cork Airport Business Park, Cork, Ireland.

**Comment by gforcada** [comment]
The problem is that ``haproxy_log_analysis`` expects a syslog slug at the beginning of every line.

This line works:
```
Dec  9 13:01:26 localhost haproxy[28029]: 10.0.2.7:58500 [22/Mar/2015:16:44:27.021] riak_rest riak_rest_backend/TRV-EU-RIAK-7 0/0/1/830/831 200 1217 - - ---- 50/50/49/8/0 0/0 "GET /search/query/sessions?q=Session.Details.IPAddresses.ClientIp:x&fl=Session.SessionId&wt=json&sort=&start=0&rows=10000000 HTTP/1.1"
```

I just created issue #10 for it.

**Comment by jethr0** [comment]
@gforcada sorry, new release isn't working too. Tried replacing all 127.0.0.1 with "localhost" and stripped most content to the minimal version of the line but still the same result:

$ haproxy_log_analysis -l logfile -c http_methods
command: http_methods
=====================-
defaultdict(<type 'int'>, {}) 

If you could send me a line thats working for you I could check if this one runs on my host too, just to make sure the environment is sane here ..

**Comment by gforcada** [comment]
@jethr0 as for python versions, code is tested against python 2.7, 3.3 and 3.4.

As for log lines that work, see any file on https://github.com/gforcada/haproxy_log_analysis/tree/master/haproxy/tests/files

You can (privately) mail me a log file (1 or 5 lines would be most probably enough) so that I can take a look at it? My email is gforcada AT gnome DOT org
